GET http://localhost:8000/finance/allTransactions

###
POST http://localhost:8000/finance/newTransaction
Content-Type: application/json

{
    "category": "food",
    "item": "pizza",
    "amount": -12
}




###
GET http://localhost:8000/finance/allJobPostings

###
POST http://localhost:8000/finance/newJobPosting
Content-Type: application/json

{
    "title": "MathGradeA",
    "salary": 10
}

###
PUT http://localhost:8000/finance/updateJobPosting/65b59bcd2572d6f471b80360
Content-Type: application/json

{
    "title": "bobaRun",
    "salary": 9
}

###
DELETE http://localhost:8000/finance/deleteJobPosting/65b59f7dad838f81563004d0





###
GET http://localhost:8000/finance/allPotentialItems

###
POST http://localhost:8000/finance/newPotentialItem
Content-Type: application/json

{
    "itemName": "Pink Fuzzy Gloves",
    "price": 8.99,
    "image": "https://i5.walmartimages.com/seo/Men-s-Women-s-Warm-Winter-Fuzzy-Cozy-Gloves-Light-Pink_6956376f-8af8-40b2-8020-ff4c5cb2e581.74ad7ac59fdc441ebd5b73cc7d5b707b.jpeg"
}

###
DELETE http://localhost:8000/finance/deletePotentialItem/65b5e686274913a3d4dec3ec





###
GET http://localhost:8000/finance/allConfirmedItems

###
POST http://localhost:8000/finance/newConfirmedItem
Content-Type: application/json

{
    "itemName": "Pink Fuzzy Gloves",
    "price": 8.99,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.walmart.com%2Fip%2FMen-s-Women-s-Warm-Winter-Fuzzy-Cozy-Gloves-White%2F774952341&psig=AOvVaw3Si1Kj0Vzv_ON-3Xd12dcy&ust=1706545584353000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCIDWxey_gIQDFQAAAAAdAAAAABAE"
}

###
DELETE http://localhost:8000/finance/deleteConfirmedItem/65b5ac31f9e668e028e105ad


